export const QUESTIONER_CONFIG_REQUEST = 'QUESTIONER_CONFIG_REQUEST';
export const QUESTIONER_CONFIG_SUCCESS = 'QUESTIONER_CONFIG_SUCCESS';
export const QUESTIONER_CONFIG_FAILURE = 'QUESTIONER_CONFIG_FAILURE';

export const SAVE_ANSWERS_REQUEST = 'SAVE_ANSWERS_REQUEST';
export const SAVE_ANSWERS_SUCCESS = 'SAVE_ANSWERS_SUCCESS';
export const SAVE_ANSWERS_FAILURE = 'SAVE_ANSWERS_FAILURE';
